document = formula

type          = type[ .* ]

formula           = predicate
                    / equality
                    / negation
                    / binary_connective
                    / quantifier formula
                    / "(" formula ")"
negation          = "!" formula
quantifier        = "forall" / "exist"
binary_connective = andor / (then / if)
andor             = formula ("and" / "or") formula
then              = formula "=>" formula
iff               = formula "<=>" formula

term       = variable / function

equality   = term "=" term

variable   = symbol
function   = symbol "(" term_list ")"
predicate  = (symbol / type) "(" term_list ")"
term_list  = term *("," term)

symbol     = *1(ALPHA / DIGIT / "+" / "-" / "*" / "/" / "^" / "_")