statement = condition

setbuilder = "{" vardec "|" condition *("," atomic) "}"
setlist    = "{" [ atomic *("," atomic) ] "}"

vardec = variable [ "in" set ]

condition = subsetin / expr
subsetin  = variable ("in" / "subset" / "subseteq") variable
expr      = variable ( "=" / "!=" / "<" / ">" / ">=" / "<=") atomic

brackets   = "(" exponents ")"
exponents  = muldiv "^" atomic
muldiv     = addsub ( "*" / "/" ) atomic
addsub     = atomic ( "+" / "-" ) atomic

atomic   = variable / number / brackets / ("-" atomic) / set
set      = setbuilder / setlist / variable
variable = ALPHA
number   = *1DIGIT

quantifier = "exists" / "forall"
implies    = "implies"